// Pre defined words up to 5 players.
export default [
  [
    'conservative',
    'supplementary',
    'rich wife',
    'inquiry',
    'compensation',
    'able',
    'future',
    'open mind',
    'prevent',
    'progressive',
  ],
  [
    'inject',
    'dark night in the mood',
    'doubt',
    'constitutional',
    'honor',
    'shine like a diamond',
    'pause',
    'shot',
    'underline',
    'appoint',
  ],
  [
    'dancing in the rain',
    'captivate',
    'runner',
    'thoughtful',
    'compose',
    'dine',
    'mask for carnaval',
    'admit',
    'favor',
    'advantage',
  ],
  [
    'personal finance',
    'guess',
    'reduction',
    'indirect',
    'prosecution',
    'seed',
    'stem',
    'problem',
    'obstacle',
    'explicit',
  ],
  ['black', 'grey', 'white', 'red', 'yellow', 'purple', 'green', 'violet', 'blue', 'brown'],
] satisfies string[][]
