name: 'expo:create-pr-preview'
on:
  push:
  pull_request:

jobs:
  create_preview:
    uses: ./.github/workflows/create-preview.yml

  comment_on_pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    steps:
      - name: Extract build IDs from build.json
        run: |
          android_id=$(cat build.json | jq -r 'map(select(has("platform") and .platform == "android")) | .[0].id')
          ios_id=$(cat build.json | jq -r 'map(select(has("platform") and .platform == "ios")) | .[0].id')
          echo "ANDROID_ID=$android_id" >> $GITHUB_ENV
          echo "IOS_ID=$ios_id" >> $GITHUB_ENV

      - name: Post comment
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            Preview builds were successfully created:
            | Android | iOS |
            | --- | --- |
            | ![Android QR Code](https://qr.expo.dev/eas-update?updateId=${{ env.ANDROID_ID }}&appScheme=exp&host=u.expo.dev) | ![iOS QR Code](https://qr.expo.dev/eas-update?updateId=${{ env.IOS_ID }}&appScheme=exp&host=u.expo.dev) |
          check_for_duplicate_msg: false
          delete_prev_regex_msg: 'Preview builds were successfully created:'
